In [2]:
import copy
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

from sequence_jacobian import het, simple, create_model              # functions
from sequence_jacobian import interpolate, grids, misc, estimation   # modules
from numba import vectorize

def household_guess(a_grid,e_grid,r,w,gamma,T):
    wel = (1+r)*a_grid[np.newaxis,:] + w*e_grid[:,np.newaxis] + T[:,np.newaxis]
    V_prime = (1+r)*(wel*0.1)**(-gamma)
    return V_prime

@het(exogenous = 'Pi',policy = 'a', backward = 'V_prime', backward_init=household_guess)
def household(V_prime_p,a_grid,e_grid,r,w,T,T_c,beta,gamma,v,phi):

    we = w*e_grid

    c_prime = ((1+T_c)*beta*V_prime_p)**(-1/gamma) #c_prime is quite a misnomer, since this is the new guess for c_t
    n_prime = (we[:,np.newaxis]/(phi*(1+T_c)*c_prime**gamma))**(1/v)

    new_grid = (c_prime + a_grid[np.newaxis,:] - we[:,np.newaxis]*n_prime - T[:,np.newaxis])
    wel = (1+r)*a_grid

    c = interpolate.interpolate_y(new_grid,wel,c_prime)
    n = interpolate.interpolate_y(new_grid,wel,n_prime)

    a = wel + we[:,np.newaxis]*n + T[:,np.newaxis] - c
    V_prime= (1+r)/(1+T_c)*c**(-gamma)

    # checks for violations of the condition of minimal assets required and fixes it

    indexes_asset = np.nonzero(a < a_grid[0]) #first dimension: labor grid, second dimension: asset grid
    a[indexes_asset] = a_grid[0]

    if indexes_asset[0].size != 0 and indexes_asset[1].size !=0:

        aa = np.zeros((indexes_asset[0].size)) + 1E-5
        rest = -a_grid[0] + wel[indexes_asset[1]] + T[indexes_asset[0]]
        bb = c[indexes_asset] + 0.5
        
        c[indexes_asset] = vec_bissection(lambda c : consumption(c,we[indexes_asset[0]],rest,gamma,v,phi),aa,bb)
        n[indexes_asset] = (we[indexes_asset[0]]/(phi*c[indexes_asset]**gamma))**(1/v)
        V_prime[indexes_asset] = (1+r)*(c[indexes_asset])**(-gamma)

    return V_prime,a,c,n

def make_grid(rho_e, sd_e, nE, amin, amax, nA):
    e_grid, pi_e, Pi = grids.markov_rouwenhorst(rho=rho_e, sigma=sd_e, N=nE)
    a_grid = grids.agrid(amin=amin, amax=amax, n=nA)
    return e_grid, Pi, a_grid, pi_e

def transfers(pi_e, Div, Tax, e_grid):
    # hardwired incidence rules are proportional to skill; scale does not matter 
    tax_rule, div_rule = e_grid, e_grid
    div = Div / np.sum(pi_e * div_rule) * div_rule
    #tax = Tax / np.sum(pi_e * tax_rule) * tax_rule
    T = div# - tax
    return T

household_inp = household.add_hetinputs([make_grid,transfers])

def labor_supply(n, e_grid):
    ne = e_grid[:, np.newaxis] * n
    return ne

hh_ext = household_inp.add_hetoutputs([labor_supply])

@simple
def firm(Y, w, Z, pi, mu, kappa):
    L = Y / Z
    Div = Y - w * L - mu/(mu-1)/(2*kappa) * (1+pi).apply(np.log)**2 * Y
    return L, Div


@simple
def monetary(pi, rstar, phi_pi):
    r = (1 + rstar(-1) + phi_pi * pi(-1)) / (1 + pi) - 1
    return r


@simple
def fiscal(r,B,C,T_c):
     = (1+r) * B(-1) - T_c*C 
    return A


@simple
def mkt_clearing(A, NE, C, L, Y, B, pi, mu, kappa):
    asset_mkt = A - B
    labor_mkt = NE - L
    goods_mkt = Y - C - mu/(mu-1)/(2*kappa) * (1+pi).apply(np.log)**2 * Y
    return asset_mkt, labor_mkt, goods_mkt


@simple
def nkpc_ss(Z, mu):
    w = Z / mu
    return w

blocks_ss = [hh_ext, firm, monetary, fiscal, mkt_clearing, nkpc_ss]

hank_ss = create_model(blocks_ss, name="One-Asset HANK SS")

print(hank_ss)
print(f"Inputs: {hank_ss.inputs}")

calibration = {'gamma': 1, 'v': 1, 'rho_e': 0.966, 'sd_e': 0.5, 'nE': 10,
               'amin': 0, 'amax': 150, 'nA': 500, 'Y': 1.0, 'Z': 1.0, 'pi': 0.0,
               'mu': 1.2, 'kappa': 0.1, 'rstar': 0.005, 'phi_pi': 1.5, 'B': 5.6, 'T_c': 0.1}

unknowns_ss = {'beta': 0.986, 'phi': 0.8}
targets_ss = {'asset_mkt': 0, 'labor_mkt': 0}

ss0 = hank_ss.solve_steady_state(calibration, unknowns_ss, targets_ss, solver="hybr")

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 86)

In [3]:
import copy
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

from sequence_jacobian import het, simple, create_model              # functions
from sequence_jacobian import interpolate, grids, misc, estimation 

In [4]:
nE = 3
rho_e =0.9
sd_e = 1.5
amin = 0.1
amax = 10
nA = 100

gamma = 1
r = 0.005
beta = 1/(1+r)

In [5]:
e_grid, pi_e, Pi = grids.markov_rouwenhorst(rho=rho_e, sigma=sd_e, N=nE)
a_grid = grids.agrid(amin=amin, amax=amax, n=nA)
z_grid = e_grid

T = np.zeros(nE)

def household_guess(a_grid,r,z_grid,gamma,T):
    new_z = np.ones((z_grid.shape[0],1))
    wel = (1+r)*a_grid[np.newaxis,:] + new_z + T[:,np.newaxis]
    V_prime = (1+r)*(wel*0.1)**(-gamma)
    return V_prime



In [20]:
V_prime_p = household_guess(a_grid,r,e_grid,gamma,T)

In [21]:
c_prime = (beta*V_prime_p)**(-1/gamma) #c_prime is quite a misnomer, since this is the new guess for c_t

new_grid = c_prime + a_grid[np.newaxis,:] - z_grid[:,np.newaxis] - T[:,np.newaxis]
wel = (1+r)*a_grid

c = interpolate.interpolate_y(new_grid,wel,c_prime)

a = wel + z_grid[:,np.newaxis] + T[:,np.newaxis] - c

In [22]:
indexes_asset = np.nonzero(a < a_grid[0])

In [23]:
indexes_asset

(array([0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4]))

In [24]:
c[indexes_asset]

array([0.10423112, 0.10556011, 0.10693186, 0.10834775, 0.10980921])

In [26]:
wel[indexes_asset[1]] + z_grid[indexes_asset[0]] + T[indexes_asset[0]] - a_grid[0]

array([0.04633179, 0.06088454, 0.07590557, 0.09140995, 0.10741325])

In [27]:
aa = a[indexes_asset] + c[indexes_asset]

In [28]:
aa

array([0.14633179, 0.16088454, 0.17590557, 0.19140995, 0.20741325])

In [29]:
if indexes_asset[0].size != 0 and indexes_asset[1].size !=0:
        
    a[indexes_asset] = a_grid[0]
        
    c[indexes_asset] = wel[indexes_asset[1]] + z_grid[indexes_asset[0]] + T[indexes_asset[0]] - a[indexes_asset]

In [30]:
V_prime_p = (1+r)*c**(-gamma)

In [31]:
a[indexes_asset]

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [32]:
c[indexes_asset]

array([0.04633179, 0.06088454, 0.07590557, 0.09140995, 0.10741325])

In [33]:
aa - (a[indexes_asset] + c[indexes_asset])

array([0., 0., 0., 0., 0.])

In [17]:
(a[indexes_asset] - c[indexes_asset])

array([ 0.05366821,  0.03911546,  0.02409443,  0.00859005, -0.00741325])